
services:
  postgres:
    image: postgres:latest
    container_name: big_data_2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: big-data-spark
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./source_data:/source_data
    networks:
      - bigdata-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
    networks:
      - bigdata-network
    environment:
      CLICKHOUSE_DB: big_data_2
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  spark:
    image: bitnami/spark:3.3
    container_name: spark
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark-apps:/app
      - ./jars:/jars
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark
      - SPARK_OPTS=--driver-java-options '-Djava.net.preferIPv4Stack=true'
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - bigdata-network

  spark-worker:
    image: bitnami/spark:3.3
    container_name: spark-worker
    depends_on:
      - spark
    volumes:
      - ./spark-apps:/spark-apps
      - ./jars:/jars
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-worker
    networks:
      - bigdata-network

volumes:
  pgdata:
  clickhouse_data:
  clickhouse_log:

networks:
  bigdata-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/19
